image: rambabusaravanan/firebase

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy-prod:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  script:
    - npm install
    - npm run build
    - firebase use formula-d --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
